-- sql server DDL Specification for OMOP staging tables
-- These tables are the temporary destination for Cerner Extracts prior to transformation steps
DROP TABLE Delphi.dbo.STG_CARE_SITE;
CREATE TABLE Delphi.dbo.STG_CARE_SITE (
            identity_context               VARCHAR(255) NOT NULL,
			care_site_id                   BIGINT NOT NULL,
			care_site_name                 VARCHAR(255) NULL,
			place_of_service_concept_id    INTEGER NULL,
			street_addr                    VARCHAR(50) NOT NULL,
			location_id                    INTEGER NULL,
			care_site_source_value         VARCHAR(50) NULL,
			place_of_service_source_value  VARCHAR(50) NULL,
            updt_dt_tm                     DATETIMEOFFSET(0) );

CREATE TABLE Delphi.dbo.STG_LOCATION (
			identity_context               VARCHAR(255) NOT NULL,
			location_id                    INTEGER NOT NULL,
			address_1                      VARCHAR(50) NULL,
			address_2                      VARCHAR(50) NULL,
			city                           VARCHAR(50) NULL,
			state                          VARCHAR(2) NULL,
			zip                            VARCHAR(9) NULL,
			county                         VARCHAR(20) NULL,
			location_source_value          VARCHAR(50) NULL,
			country_concept_id             INTEGER NULL,
			country_source_value           VARCHAR(80) NULL,
			latitude                       FLOAT NULL,
			longitude                      FLOAT NULL,
            updt_dt_tm                     DATETIMEOFFSET(0) );

CREATE TABLE Delphi.dbo.STG_PROVIDER (
			identity_context               VARCHAR(255) NOT NULL,
			provider_id                    INTEGER NOT NULL,
			provider_name                  VARCHAR(255) NULL,
			npi                            VARCHAR(20) NULL,
			dea                            VARCHAR(20) NULL,
			specialty_concept_id           INTEGER NULL,
			care_site_id                   BIGINT NULL,
			year_of_birth                  INTEGER NULL,
			gender_concept_id              INTEGER NULL,
			provider_source_value          VARCHAR(50) NULL,
			specialty_source_value         VARCHAR(50) NULL,
			specialty_source_concept_id    INTEGER NULL,
			gender_source_value            VARCHAR(50) NULL,
			gender_source_concept_id       INTEGER NULL,
        	updt_dt_tm                     DATETIMEOFFSET(0) );

CREATE TABLE Delphi.dbo.STG_PERSON (
			identity_context               VARCHAR(255) NOT NULL,
			person_id                      INTEGER NOT NULL,
			gender_concept_id              INTEGER NOT NULL,
			year_of_birth                  INTEGER NOT NULL,
			month_of_birth                 INTEGER NULL,
			day_of_birth                   INTEGER NULL,
			birth_datetime                 DATETIME NULL,
			race_concept_id                INTEGER NOT NULL,
			ethnicity_concept_id           INTEGER NOT NULL,
			location_id                    INTEGER NULL,
			provider_id                    INTEGER NULL,
			care_site_id                   BIGINT NULL,
			person_source_value            VARCHAR(50) NULL,
			gender_source_value            VARCHAR(50) NULL,
			gender_source_concept_id       INTEGER NULL,
			race_source_value              VARCHAR(50) NULL,
			race_source_concept_id         INTEGER NULL,
			ethnicity_source_value         VARCHAR(50) NULL,
			ethnicity_source_concept_id    INTEGER NULL,
            updt_dt_tm                     DATETIMEOFFSET(0) );

CREATE TABLE Delphi.dbo.STG_VISIT_OCCURRENCE (
			identity_context               VARCHAR(255) NOT NULL,
			visit_occurrence_id            INTEGER NOT NULL,
			person_id                      INTEGER NOT NULL,
			visit_concept_id               INTEGER NOT NULL,
			visit_start_date               DATE NOT NULL,
			visit_start_datetime           DATETIME NULL,
			visit_end_date                 DATE NOT NULL,
			visit_end_datetime             DATETIME NULL,
			visit_type_concept_id          INTEGER NOT NULL,
			provider_id                    INTEGER NULL,
			care_site_id                   BIGINT NULL,
			visit_source_value             VARCHAR(50) NULL,
			visit_source_concept_id        INTEGER NULL,
			admitted_from_concept_id       INTEGER NULL,
			admitted_from_source_value     VARCHAR(50) NULL,
			discharged_to_concept_id       INTEGER NULL,
			discharged_to_source_value     VARCHAR(50) NULL,
			preceding_visit_occurrence_id  INTEGER NULL,
            updt_dt_tm                     DATETIMEOFFSET(0) );

CREATE TABLE Delphi.dbo.STG_VISIT_DETAIL (
			identity_context               VARCHAR(255) NOT NULL,
			visit_detail_id                INTEGER NOT NULL,
			person_id                      INTEGER NOT NULL,
			visit_detail_concept_id        INTEGER NOT NULL,
			visit_detail_start_date        DATE NOT NULL,
			visit_detail_start_datetime    DATETIME NULL,
			visit_detail_end_date          DATE NOT NULL,
			visit_detail_end_datetime      DATETIME NULL,
			visit_detail_type_concept_id   INTEGER NOT NULL,
			provider_id                    INTEGER NULL,
			care_site_id                   BIGINT NULL,
			visit_detail_source_value      VARCHAR(50) NULL,
			visit_detail_source_concept_id INTEGER NULL,
			admitted_from_concept_id       INTEGER NULL,
			admitted_from_source_value     VARCHAR(50) NULL,
			discharged_to_source_value     VARCHAR(50) NULL,
			discharged_to_concept_id       INTEGER NULL,
			preceding_visit_detail_id      INTEGER NULL,
			parent_visit_detail_id         INTEGER NULL,
			visit_occurrence_id            INTEGER NOT NULL,
            updt_dt_tm                     DATETIMEOFFSET(0) );

CREATE TABLE Delphi.dbo.STG_CONDITION_OCCURRENCE (
			identity_context               VARCHAR(255) NOT NULL,
			condition_occurrence_id        INTEGER NOT NULL,
			person_id                      INTEGER NOT NULL,
			condition_concept_id           INTEGER NOT NULL,
			condition_start_date           DATE NOT NULL,
			condition_start_datetime       DATETIME NULL,
			condition_end_date             DATE NULL,
			condition_end_datetime         DATETIME NULL,
			condition_type_concept_id      INTEGER NOT NULL,
			condition_status_concept_id    INTEGER NULL,
			stop_reason                    VARCHAR(20) NULL,
			provider_id                    INTEGER NULL,
			visit_occurrence_id            INTEGER NULL,
			visit_detail_id                INTEGER NULL,
			condition_source_value         VARCHAR(50) NULL,
			condition_source_concept_id    INTEGER NULL,
			condition_status_source_value  VARCHAR(50) NULL,
                        updt_dt_tm                     DATETIMEOFFSET(0) );

CREATE TABLE Delphi.dbo.STG_PROCEDURE_OCCURRENCE (
			identity_context               VARCHAR(255) NOT NULL,
			procedure_occurrence_id        INTEGER NOT NULL,
			person_id                      INTEGER NOT NULL,
			procedure_concept_id           INTEGER NOT NULL,
			procedure_date                 DATE NOT NULL,
			procedure_datetime             DATETIME NULL,
			procedure_end_date             DATE NULL,
			procedure_end_datetime         DATETIME NULL,
			procedure_type_concept_id      INTEGER NOT NULL,
			modifier_concept_id            INTEGER NULL,
			quantity                       INTEGER NULL,
			provider_id                    INTEGER NULL,
			visit_occurrence_id            INTEGER NULL,
			visit_detail_id                INTEGER NULL,
			procedure_source_value         VARCHAR(50) NULL,
			procedure_source_concept_id    INTEGER NULL,
			modifier_source_value          VARCHAR(50) NULL,
            updt_dt_tm                     DATETIMEOFFSET(0) );

CREATE TABLE Delphi.dbo.STG_DRUG_EXPOSURE (
			identity_context               VARCHAR(255) NOT NULL,
			drug_exposure_id               INTEGER NOT NULL,
			person_id                      INTEGER NOT NULL,
			drug_concept_id                INTEGER NOT NULL,
			drug_exposure_start_date       DATE NOT NULL,
			drug_exposure_start_datetime   DATETIME NULL,
			drug_exposure_end_date         DATE NOT NULL,
			drug_exposure_end_datetime     DATETIME NULL,
			verbatim_end_date              DATE NULL,
			drug_type_concept_id           INTEGER NOT NULL,
			stop_reason                    VARCHAR(20) NULL,
			refills                        INTEGER NULL,
			quantity                       FLOAT NULL,
			days_supply                    INTEGER NULL,
			sig                            VARCHAR(MAX) NULL,
			route_concept_id               INTEGER NULL,
			lot_number                     VARCHAR(50) NULL,
			provider_id                    INTEGER NULL,
			visit_occurrence_id            INTEGER NULL,
			visit_detail_id                INTEGER NULL,
			drug_source_value              VARCHAR(50) NULL,
			drug_source_concept_id         INTEGER NULL,
			route_source_value             VARCHAR(50) NULL,
			dose_unit_source_value         VARCHAR(50) NULL,
            updt_dt_tm                     DATETIMEOFFSET(0) );

CREATE TABLE Delphi.dbo.STG_OBSERVATION (
            identity_context               VARCHAR(25),
            observation_id                 VARCHAR(100),
            person_id                      INTEGER,
            event_cd                       INTEGER,
            observation_date               DATE,
            observation_DATETIME           DATETIMEOFFSET, -- TIMESTAMPTZ equivalent
            observation_type_concept_id    INTEGER,
            form_description               VARCHAR(400),
            section_description            VARCHAR(400),
            description                    VARCHAR(712),
            value_as_number                INTEGER,
            value_as_string                VARCHAR(510),
            value_as_concept_id            INTEGER,
            qualifier_concept_id           INTEGER,
            unit_concept_id                INTEGER,
            provider_id                    INTEGER,
            visit_occurrence_id            INTEGER,
            visit_detail_id                VARCHAR(100),
            observation_source_value       VARCHAR(100),
            observation_source_concept_id  VARCHAR(100),
            unit_source_value              VARCHAR(100),
            qualifier_source_id            VARCHAR(100),
            value_source_value             VARCHAR(100),
            observation_event_id           VARCHAR(100),
            obs_event_field_concept_id     VARCHAR(100),
            updt_dt_tm                     DATETIMEOFFSET(0) );

CREATE TABLE Delphi.dbo.STG_OBSERVATION_FINAL (
            identity_context               VARCHAR(25),
            observation_id                 VARCHAR(100),
            person_id                      INTEGER,
            event_cd                       INTEGER,
            observation_date               DATE,
            observation_datetime           DATETIMEOFFSET(0), -- TIMESTAMPTZ equivalent
            observation_type_concept_id    INTEGER,
            form_description               VARCHAR(400),
            section_description            VARCHAR(400),
            description                    VARCHAR(712),
            value_as_number                INTEGER,
            value_as_string                VARCHAR(510),
            value_as_concept_id            INTEGER,
            qualifier_concept_id           INTEGER,
            unit_concept_id                INTEGER,
            provider_id                    INTEGER,
            visit_occurrence_id            INTEGER,
            visit_detail_id                VARCHAR(100),
            observation_source_value       VARCHAR(100),
            observation_source_concept_id  VARCHAR(100),
            unit_source_value              VARCHAR(100),
            qualifier_source_id            VARCHAR(100),
            value_source_value             VARCHAR(100),
            observation_event_id           VARCHAR(100),
            obs_event_field_concept_id     VARCHAR(100),
            updt_dt_tm                     DATETIMEOFFSET(0) );

CREATE TABLE Delphi.dbo.STG_SPECIMEN (
			identity_context               VARCHAR(255) NOT NULL,
			specimen_id                    INTEGER NOT NULL,
			person_id                      INTEGER NOT NULL,
			specimen_concept_id            INTEGER NOT NULL,
			specimen_type_concept_id       INTEGER NOT NULL,
			specimen_date                  DATE NOT NULL,
			specimen_datetime              DATETIME NULL,
			quantity                       FLOAT NULL,
			unit_concept_id                INTEGER NULL,
			anatomic_site_concept_id       INTEGER NULL,
			disease_status_concept_id      INTEGER NULL,
			specimen_source_id             VARCHAR(50) NULL,
			specimen_source_value          VARCHAR(50) NULL,
			unit_source_value              VARCHAR(50) NULL,
			anatomic_site_source_value     VARCHAR(50) NULL,
			disease_status_source_value    VARCHAR(50) NULL,
            updt_dt_tm                     DATETIMEOFFSET(0) );

CREATE TABLE Delphi.dbo.STG_MEASUREMENT (
			identity_context               VARCHAR(255) NOT NULL,
			measurement_id                 INTEGER NOT NULL,
			person_id                      INTEGER NOT NULL,
			measurement_concept_id         INTEGER NOT NULL,
			measurement_date               DATE NOT NULL,
			measurement_datetime           DATETIME NULL,
			measurement_time               VARCHAR(10) NULL,
			measurement_type_concept_id    INTEGER NOT NULL,
			operator_concept_id            INTEGER NULL,
			value_as_number                FLOAT NULL,
			value_as_concept_id            INTEGER NULL,
			unit_concept_id                INTEGER NULL,
			range_low                      FLOAT NULL,
			range_high                     FLOAT NULL,
			provider_id                    INTEGER NULL,
			visit_occurrence_id            INTEGER NULL,
			visit_detail_id                INTEGER NULL,
			measurement_source_value       VARCHAR(50) NULL,
			measurement_source_concept_id  INTEGER NULL,
			unit_source_value              VARCHAR(50) NULL,
			unit_source_concept_id         INTEGER NULL,
			value_source_value             VARCHAR(50) NULL,
			measurement_event_id           BIGINT NULL,
			meas_event_field_concept_id    INTEGER NULL,
            updt_dt_tm                     DATETIMEOFFSET(0) );

-- TODO: Datatypes for this table need to be checked/verified
CREATE TABLE Delphi.dbo.OMOP_CODE_VALUE (
            code_id                        INTEGER,
            code_display                   VARCHAR(100),
            code_type                      VARCHAR(100),
            table_used                     VARCHAR(100),
            column_used                    VARCHAR(400) );
